### PR TITLE
Fix server crash with TES3MP v0.8.1

### LINKED ISSUE #1: 0.81 compatibility
Change line 304 (main.lua) from:

    player:SaveStatsDynamic()
to:
    player:SaveStatsDynamic(player.data)

### PR DESCRIPTION
**Pull request by backlabs1**
Closes #1.

### CODE REVIEW

**Comment by hristoast** [comment]
Hey @backlabs1 - thanks for doing this! I haven't ran this locally yet but I assume it works on your end? I'd like to try it before merging in any case and will try to do that soon.

**Comment by backlabs1** [comment]
Yes, I have tested it with TES3MP v0.8.1. It fixes the crash and also fixes the problem described in [my comment](https://github.com/hristoast/tes3mp-mmar/issues/1#issuecomment-1298006261).

**Comment by backlabs1** [comment]
I'm glad for you to go ahead and test it yourself anyway! As the author you have a better idea about exactly what you need to test for. Thanks!

**Comment by Teirdalin** [comment]
You're an absolute hero, this change fixes my crashes.

**Comment by backlabs1** [comment]
@Teirdalin, I'm glad it helped and thanks for your feedback!

**Pull request merged**
